name: "execkpi_dbt"
version: "1.0.0"
profile: "execkpi_profile"

model-paths: ["models"]

models:
  execkpi_dbt:
    +materialized: view
    +schema: execkpi     # BigQuery dataset name

    silver:
      +materialized: view
    gold:
      +materialized: view
