version: 2

models:
  - name: revenue_daily
    description: Daily orders/revenue/AOV (completed orders)
    columns:
      - name: day
        tests:
          - not_null

  - name: funnel_users
    description: Per-user funnel flags; conversion comes from completed orders
    columns:
      - name: user_id
        tests:
          - not_null
      - name: converted
        tests:
          - accepted_values:
              values: [true, false]
              quote: false
